config/routes.rb
Receptionist::Application.routes.draw do
  devise_for :users

	resources :identities

  resources :permissions

  resources :orgranizations

	resource :user

	resources :utilizations

  resources :resources do |r|
		member do
			get :utilize
			get :dashboard
			
			get :open
			get :close
		end
	end

	root :to => "utilizations#index"
end

app/models/utilization.rb
class Utilization < ActiveRecord::Base
	belongs_to :resource
	belongs_to :identity
	
	data_fabric :replicated => true
end

app/controllers/utilizations_controller.rb
class UtilizationsController < ApplicationController
	
	def index
		@utilizations = Utilization.all(:limit=>10, :order =>'created_at desc')
		
		respond_to do |format|
			format.js {
				render :partial => 'utilization', :collection => @utilizations
			}
			format.html {
			}
			format.json {
				render :text => @utilizations.to_json(
				:only => [:created_at],
				:include => {:resource => {
					:only => [:name]
				} ,:identity => {
					:include => {:user => {
						:only => [:name,:email,:avatar_file_name,:avatar_content_type]
					}}, :only => [:authorizations_count]
				}})
			}
		end
	end
	
end

app/views/utilizations/_utilization.erb
<li>
<%=image_tag utilization.identity.user.avatar? ? utilization.identity.user.avatar.url(:small) : utilization.identity.user.gravatar, :class => 'small-user-avatar', :alt => utilization.identity.user %>
<%= utilization.identity.user %> @ <%=link_to utilization.resource.name, utilization.resource %> - <%=time_ago_in_words(utilization.created_at)%> ago</li>

app/views/utilizations/index.html.erb
<ul id="recent-activity">
</ul>

<% content_for :head do %>
	<script type="text/javascript">
	
		function reload_activity() {
			$.ajax({
				url: <%=utilizations_path.to_json.html_safe%>,
				success: function(data) {
					$('#recent-activity').html(data);
				}
			});

			setTimeout(function() {
				reload_activity();
			}, 10000);
		}
	
		$(function() {
			reload_activity();
		});
	</script>
<% end %>