config/routes.rb
Receptionist::Application.routes.draw do
  devise_for :users

	resources :identities

  resources :permissions

  resources :orgranizations

	resource :user

	resources :utilizations

  resources :resources do |r|
		member do
			get :utilize
			get :dashboard
			
			get :open
			get :close
		end
	end

	root :to => "utilizations#index"
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
	has_many :identities
	belongs_to :organization

  data_fabric :replicated => true
	
	has_many :permissions, :as => :object
	has_many :resources, :through => :permissions

  has_attached_file :avatar, :styles => { :medium => "300x300>", :small => "100x100>" }
	
	# Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :oauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :phone, :avatar

	def to_s
		name? ? name : email
	end
	
	def gravatar
    email_address = self.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    image_src = "http://www.gravatar.com/avatar/#{hash}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		if params[:id] then
			@user = User.find(params[:id])
		else
			@user = current_user
		end
	end
	
	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update_attributes(params[:user]) then
			flash[:notice] = 'Successfully updated your details.'
			redirect_to user_path
		else
			flash[:error] = 'We were unable to update your details.'
			render :edit
		end
	end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<ul>
	<%= form_for @user, :html => { :multipart => true } do |f| %>
		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</li>

		<li>
			<%=f.label :email %>
			<%= f.text_field :email %>
		</li>

		<li>
			<%=f.label :phone %>
			<%= f.text_field :phone %>
		</li>

		<li>
			<%=f.label :avatar %>
			<%=f.file_field :avatar %>
		</li>
		
		<%= f.submit %>
	<% end %>
</ul>

app/views/users/show.html.erb
<h1>About Me</h1>

<%=image_tag @user.avatar.url(:small) %>

<ul>
	<li><strong>Name</strong> <%=@user.name%></li>
	<li><strong>Email</strong> <%=@user.email%></li>
</ul>

<%=link_to 'Edit My Details', edit_user_path %>

<%=link_to 'Change My Password', edit_user_registration_path %>

<h2>My Accounts</h2>

<ul>
	<% @user.identities.each {|a| %>
		<li><%=link_to a.name, a.becomes(Identity)%></li>
	<% } %>
	<li><%=link_to 'Register Identity', new_identity_path %></li>
</ul>

<h2>My Permissions</h2>

<ul>
	<% @user.permissions.each {|p| 
		next unless p.resource
		%>
		<li><%=link_to p.resource.name, p.resource %></li>
	<% } %>
</ul>