config/routes.rb
Receptionist::Application.routes.draw do
  devise_for :users

	resources :identities

  resources :permissions

  resources :orgranizations

	resource :user

	resources :utilizations

  resources :resources do |r|
		member do
			get :utilize
			get :dashboard
			
			get :open
			get :close
		end
	end

	root :to => "utilizations#index"
end

app/views/resources/_form.html.erb
<ul>

<% form_for @resource do |f| %>
	
	<li>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</li>
	
	<li>
		<%=f.label :description %>
		<%= f.text_field :description %>
	</li>
	
	<li>
		<%=f.label :is_guarded %>
		<%=f.check_box :is_guarded%>
	</li>
	
	<li>
		<%=f.label :utilization_code %>
		<%=f.text_area :utilization_code %>
	</li>
	
	<li>
		<%=f.label :completion_code %>
		<%=f.text_area :completion_code %>
	</li>
	
	<li>
		<%=f.label :utilization_length %>
		<%=f.text_field :utilization_length %>
	</li>

	<%= f.submit %>
<% end %>

</ul>

app/views/resources/dashboard.html.erb
<% content_for :head do %>
	<script src="http://<%=request.host%>:8080/application.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
	  var jug = new Juggernaut;
	  jug.subscribe('/resources/<%=@resource.id%>/log', function(data){
	    console.log("Got log: " + data);
		$('#resource_log').append('<p>' + data + '</p>');
	  });
	  jug.subscribe('/resources/<%=@resource.id%>/status', function(data){
	    console.log("Got utilization status: " + data);
		switch(data) {
			case 'utilizing':
				$('body').css('background-color','green');
				$('#dashboard-status').html('<%=@resource.names[:open]%>');
				break;
			case 'not-utilizing':
				$('body').css('background-color','#EBEBEB');
				$('#dashboard-status').html('<%=@resource.names[:closed]%>');
				break;
		}
	  });
	</script>
<% end %>

<h1 id="dashboard-title"><%=@resource.name%></h1>

<h2 id="dashboard-status"><%=@resource.currently_utilizing ? @resource.names[:open] : @resource.names[:closed]%></h2>

<div id="resource_log">
</div>

app/views/resources/index.html.erb
<h2>Resources</h2>

<ul>
	<% @resources.each {|r| %>
		<li><%= link_to r.name,r %></li>
	<% } %>
	<li><%= link_to 'New Resource', new_resource_path %></li>
</ul>

app/views/resources/new.html.erb
<%=render :partial => 'form' %>

app/views/resources/show.html.erb
<h1><%=@resource.name%></h1>

<% if @resource.can_utilize?(current_user.identities.first) then %>
You <strong>can</strong> utilize this resource. <%=link_to 'Utilize it!', utilize_resource_path(@resource)%>

<%  if @resource.currently_utilizing then %>
	This resource is currently being utilized.
	<%=link_to 'Close it.', close_resource_path(@resource) %>
<% else %>
	<%=link_to 'Open it.', open_resource_path(@resource) unless @resource.currently_utilizing %>
<% end %>

<% end %>

<% if current_user.admin then %>
	<%=render :partial => 'form' %>

	<h4>Permissions</h4>
	<%=link_to 'New Permission', new_permission_path(:resource_id => @resource.id) %>
<% end %>